[FIX] crm_executive_dashboard - Fix asset bundle inheritance blocking module installation
The assets.xml file was using:
1. Wildcard paths (*.js, *.css) which are not supported in Odoo 17
2. inherit_id='web.assets_backend' which may not exist in all installations

This was blocking ANY module installation with error:
ValueError: External ID not found in the system: web.assets_backend

Fix: Commented out asset inheritance to allow system to function.
Note: Re-enable assets by listing files individually if needed.